#!/bin/bash

################################################################################
### 全てのホストの指定されたファイルの md5 ハッシュを表示
################################################################################

source "$(dirname "$0")"/ALLHOST-functions

if [ $# -eq 0 ]; then
	exit 1
fi

set -e
	
function main
{
	local infiles
	infiles=$(
		for i in "$@"; do
			fullpath "$i"
		done
	)
	
	for H in $(gethosts); do
		echo "$infiles" | ssh $H '
		
			H=$(echo -e "\t'$H'")
			
			while read F; do
				if [ -f "$F" ]; then
					echo "$(md5sum "$F")$H"
				elif [ -d "$F" ]; then
					for X in $(ls "$F"); do
						echo "$(md5sum "$F/$X")$H"
					done
				else
					echo "--------------------------------  $F$H"
				fi
			done
		'
	done
}

main "$@" | sort -k 2
